"""CRUD workload: INSERT / SELECT / UPDATE / DELETE on the products table.

Each cycle emits a parent 'crud.cycle' span that wraps four child spans
generated by the OTel DBAPI instrumentation on the connection cursor.
"""

import logging
import random
import time

from opentelemetry import trace

from app.otel import metrics as otel_metrics

logger = logging.getLogger(__name__)
tracer = trace.get_tracer("oracle.workload.crud", tracer_provider=None)

_CATEGORIES = ["Electronics", "Furniture", "Appliances", "Footwear", "Sports", "Books", "Garden"]
_ADJECTIVES = ["Premium", "Compact", "Deluxe", "Pro", "Essential", "Smart", "Eco"]
_NOUNS = ["Widget", "Gadget", "Device", "Tool", "Unit", "Module", "Component"]


def _random_product_name() -> str:
    return f"{random.choice(_ADJECTIVES)} {random.choice(_NOUNS)} {random.randint(100, 999)}"


def run_crud_cycle(conn) -> None:
    """Execute one full CRUD cycle and record metrics."""
    with tracer.start_as_current_span("crud.cycle") as span:
        product_id = _insert_product(conn, span)
        if product_id:
            _select_product(conn, product_id)
            _update_product(conn, product_id)
            _delete_product(conn, product_id)


def _insert_product(conn, span) -> int | None:
    name = _random_product_name()
    category = random.choice(_CATEGORIES)
    price = round(random.uniform(9.99, 1999.99), 2)
    stock_qty = random.randint(1, 500)

    t0 = time.perf_counter()
    try:
        with conn.cursor() as cur:
            cur.execute(
                """INSERT INTO products (name, category, price, stock_qty)
                   VALUES (:name, :category, :price, :stock_qty)
                   RETURNING id INTO :out_id""",
                name=name,
                category=category,
                price=price,
                stock_qty=stock_qty,
                out_id=cur.var(int),
            )
            out_id = cur.bindvars["out_id"].getvalue()
            product_id = int(out_id[0]) if isinstance(out_id, list) else int(out_id)
        conn.commit()
        duration_ms = (time.perf_counter() - t0) * 1000
        otel_metrics.query_duration_histogram.record(duration_ms, {"operation": "insert"})
        otel_metrics.db_operation_counter.add(1, {"operation": "insert"})
        span.set_attribute("product.id", product_id)
        span.set_attribute("product.name", name)
        return product_id
    except Exception as exc:
        otel_metrics.db_error_counter.add(
            1, {"error_type": type(exc).__name__, "operation": "insert"}
        )
        logger.exception("INSERT failed")
        return None


def _select_product(conn, product_id: int) -> None:
    t0 = time.perf_counter()
    try:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT id, name, category, price, stock_qty FROM products WHERE id = :id",
                id=product_id,
            )
            cur.fetchone()
        duration_ms = (time.perf_counter() - t0) * 1000
        otel_metrics.query_duration_histogram.record(duration_ms, {"operation": "select"})
        otel_metrics.db_operation_counter.add(1, {"operation": "select"})
    except Exception as exc:
        otel_metrics.db_error_counter.add(
            1, {"error_type": type(exc).__name__, "operation": "select"}
        )
        logger.exception("SELECT failed for id=%d", product_id)


def _update_product(conn, product_id: int) -> None:
    new_price = round(random.uniform(9.99, 1999.99), 2)
    t0 = time.perf_counter()
    try:
        with conn.cursor() as cur:
            cur.execute(
                "UPDATE products SET price = :price, updated_at = CURRENT_TIMESTAMP WHERE id = :id",
                price=new_price,
                id=product_id,
            )
        conn.commit()
        duration_ms = (time.perf_counter() - t0) * 1000
        otel_metrics.query_duration_histogram.record(duration_ms, {"operation": "update"})
        otel_metrics.db_operation_counter.add(1, {"operation": "update"})
    except Exception as exc:
        otel_metrics.db_error_counter.add(
            1, {"error_type": type(exc).__name__, "operation": "update"}
        )
        logger.exception("UPDATE failed for id=%d", product_id)


def _delete_product(conn, product_id: int) -> None:
    t0 = time.perf_counter()
    try:
        with conn.cursor() as cur:
            cur.execute("DELETE FROM products WHERE id = :id", id=product_id)
        conn.commit()
        duration_ms = (time.perf_counter() - t0) * 1000
        otel_metrics.query_duration_histogram.record(duration_ms, {"operation": "delete"})
        otel_metrics.db_operation_counter.add(1, {"operation": "delete"})
    except Exception as exc:
        otel_metrics.db_error_counter.add(
            1, {"error_type": type(exc).__name__, "operation": "delete"}
        )
        logger.exception("DELETE failed for id=%d", product_id)
